config/routes.rb
Rails.application.routes.draw do
  resources :domains, id: /[^\/?]+/

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/domain.rb
class Domain < ApplicationRecord
  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: %i[ show edit update destroy ]

  # GET /domains or /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1 or /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains or /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to domain_url(@domain), notice: "Domain was successfully created." }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1 or /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to domain_url(@domain), notice: "Domain was successfully updated." }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1 or /domains/1.json
  def destroy
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url, notice: "Domain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find_by!(name: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_domain.html.erb
<div id="<%= dom_id domain %>">
  <p>
    <strong>Name:</strong>
    <%= domain.name %>
  </p>

</div>

app/views/domains/_form.html.erb
<%= form_with(model: domain) do |form| %>
  <% if domain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
        <% domain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render "form", domain: @domain %>

<br>

<div>
  <%= link_to "Show this domain", @domain %> |
  <%= link_to "Back to domains", domains_path %>
</div>

app/views/domains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Domains</h1>

<div id="domains">
  <% @domains.each do |domain| %>
    <%= render domain %>
    <p>
      <%= link_to "Show this domain", domain %>
    </p>
  <% end %>
</div>

<%= link_to "New domain", new_domain_path %>

app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render "form", domain: @domain %>

<br>

<div>
  <%= link_to "Back to domains", domains_path %>
</div>

app/views/domains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @domain %>

<div>
  <%= link_to "Edit this domain", edit_domain_path(@domain) %> |
  <%= link_to "Back to domains", domains_path %>

  <%= button_to "Destroy this domain", @domain, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RouteConstraints</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>